source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'SwiftyJSON'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'CryptoSwift'
pod 'AEXML'
pod "SpringIndicator"
pod 'Alamofire', '~> 3.0'
pod 'Google/SignIn'
pod 'Google/AppInvite', '~> 1.0.2'
pod 'TMTumblrSDK'
pod "OAuthSwift", "~> 0.5.0"
