source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'SwiftyJSON', '~> 2.3.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'CryptoSwift'
pod 'AEXML'
pod "SpringIndicator"
pod 'Alamofire', '~> 3.0'
pod 'Google/SignIn'
